"use client";

import { useState, type FormEvent } from "react";
import Link from "next/link";
import { AuthCard, AuthHeader, AuthFooter, FormField } from "@/components/auth";

export default function JoinPage() {
  const [inviteCode, setInviteCode] = useState("");
  const [displayName, setDisplayName] = useState("");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");

  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError("");

    if (!inviteCode.trim()) {
      setError("Please enter your invite code.");
      return;
    }
    if (!displayName.trim()) {
      setError("Please enter your display name.");
      return;
    }
    if (!username.trim()) {
      setError("Please choose a username.");
      return;
    }
    if (!password) {
      setError("Please enter a password.");
      return;
    }
    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }
    if (password.length < 8) {
      setError("Password must be at least 8 characters.");
      return;
    }

    setIsLoading(true);
    setTimeout(() => setIsLoading(false), 1000);
  }

  return (
    <AuthCard>
      <AuthHeader
        title="Join Team"
        subtitle="Invitations are generated by the workspace owner. You must have received an invite code to register."
      />

      <form onSubmit={handleSubmit} className="gap-sm flex flex-col" noValidate>
        <FormField
          label="Invite Code"
          type="text"
          placeholder="XXXX-XXXX-XXXX"
          value={inviteCode}
          onChange={(e) => setInviteCode(e.target.value)}
          disabled={isLoading}
          required
          helperText="Enter the code from your invitation."
        />

        <div className="gap-sm grid grid-cols-1 sm:grid-cols-2">
          <FormField
            label="Display Name"
            type="text"
            placeholder="Your name"
            value={displayName}
            onChange={(e) => setDisplayName(e.target.value)}
            disabled={isLoading}
            required
          />
          <FormField
            label="Username"
            type="text"
            placeholder="Choose a username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            disabled={isLoading}
            required
          />
        </div>

        <FormField
          label="Password"
          type="password"
          placeholder="At least 8 characters"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          disabled={isLoading}
          required
          autoComplete="new-password"
        />

        <FormField
          label="Confirm Password"
          type="password"
          placeholder="Repeat your password"
          value={confirmPassword}
          onChange={(e) => setConfirmPassword(e.target.value)}
          disabled={isLoading}
          required
          autoComplete="new-password"
        />

        {error && (
          <p
            role="alert"
            className="border-error-container/30 bg-error-container/5 px-sm py-xs text-error rounded border font-mono text-[10px]"
          >
            {error}
          </p>
        )}

        <button
          type="submit"
          disabled={isLoading}
          className="gap-sm bg-primary px-md py-sm text-body-sm text-on-primary inline-flex w-full items-center justify-center rounded font-medium transition-all hover:bg-[#c01826] disabled:pointer-events-none disabled:opacity-50"
        >
          {isLoading ? (
            <>
              <div className="border-on-primary h-4 w-4 animate-spin rounded-full border-2 border-t-transparent" />
              Joining...
            </>
          ) : (
            "Join Team"
          )}
        </button>
      </form>

      <AuthFooter>
        <p className="text-body-sm text-on-surface-variant">
          Already have an account?{" "}
          <Link
            href="/login"
            className="text-primary transition-opacity hover:opacity-80"
          >
            Sign In
          </Link>
        </p>
      </AuthFooter>
    </AuthCard>
  );
}
