-- Fix auth_rls_initplan warnings: wrap auth.role() in SELECT to avoid per-row re-evaluation
-- See https://supabase.com/docs/guides/database/postgres/row-level-security#call-functions-with-select

drop policy if exists "Authenticated users can read hackathons" on public.hackathons;
drop policy if exists "Authenticated users can create hackathons" on public.hackathons;
drop policy if exists "Authenticated users can update hackathons" on public.hackathons;
drop policy if exists "Authenticated users can delete hackathons" on public.hackathons;
drop policy if exists "Owner can read invitations" on public.invitations;
drop policy if exists "Owner can create invitations" on public.invitations;
drop policy if exists "Owner can update invitations" on public.invitations;
drop policy if exists "Owner can delete invitations" on public.invitations;
drop policy if exists "Anyone can read profiles" on public.profiles;
drop policy if exists "Anyone can read team members" on public.team_members;
drop policy if exists "Owners can manage team members" on public.team_members;
drop policy if exists "Owners can update team members" on public.team_members;
drop policy if exists "Auth users read objectives" on public.objectives;
drop policy if exists "Auth users insert objectives" on public.objectives;
drop policy if exists "Auth users update objectives" on public.objectives;
drop policy if exists "Auth users delete objectives" on public.objectives;
drop policy if exists "Auth users read milestones" on public.milestones;
drop policy if exists "Auth users insert milestones" on public.milestones;
drop policy if exists "Auth users update milestones" on public.milestones;
drop policy if exists "Auth users delete milestones" on public.milestones;
drop policy if exists "Auth users read deliverables" on public.deliverables;
drop policy if exists "Auth users insert deliverables" on public.deliverables;
drop policy if exists "Auth users update deliverables" on public.deliverables;
drop policy if exists "Auth users delete deliverables" on public.deliverables;
drop policy if exists "Auth users read requirements" on public.requirements;
drop policy if exists "Auth users insert requirements" on public.requirements;
drop policy if exists "Auth users update requirements" on public.requirements;
drop policy if exists "Auth users delete requirements" on public.requirements;
drop policy if exists "Auth users read risks" on public.risks;
drop policy if exists "Auth users insert risks" on public.risks;
drop policy if exists "Auth users update risks" on public.risks;
drop policy if exists "Auth users delete risks" on public.risks;
drop policy if exists "Auth users read decisions" on public.decisions;
drop policy if exists "Auth users insert decisions" on public.decisions;
drop policy if exists "Auth users update decisions" on public.decisions;
drop policy if exists "Auth users delete decisions" on public.decisions;
drop policy if exists "Auth users read checklist_templates" on public.checklist_templates;
drop policy if exists "Auth users insert checklist_templates" on public.checklist_templates;
drop policy if exists "Auth users update checklist_templates" on public.checklist_templates;
drop policy if exists "Auth users delete checklist_templates" on public.checklist_templates;
drop policy if exists "Auth users read checklist_items" on public.checklist_items;
drop policy if exists "Auth users insert checklist_items" on public.checklist_items;
drop policy if exists "Auth users update checklist_items" on public.checklist_items;
drop policy if exists "Auth users delete checklist_items" on public.checklist_items;
drop policy if exists "Auth users read planning_notes" on public.planning_notes;
drop policy if exists "Auth users insert planning_notes" on public.planning_notes;
drop policy if exists "Auth users update planning_notes" on public.planning_notes;
drop policy if exists "Auth users delete planning_notes" on public.planning_notes;
drop policy if exists "Auth read ideas" on public.ideas;
drop policy if exists "Auth insert ideas" on public.ideas;
drop policy if exists "Auth update ideas" on public.ideas;
drop policy if exists "Auth delete ideas" on public.ideas;
drop policy if exists "Auth read votes" on public.idea_votes;
drop policy if exists "Auth insert votes" on public.idea_votes;
drop policy if exists "Auth delete votes" on public.idea_votes;
drop policy if exists "Auth read research" on public.research_items;
drop policy if exists "Auth insert research" on public.research_items;
drop policy if exists "Auth update research" on public.research_items;
drop policy if exists "Auth delete research" on public.research_items;
drop policy if exists "Auth read tasks" on public.tasks;
drop policy if exists "Auth insert tasks" on public.tasks;
drop policy if exists "Auth update tasks" on public.tasks;
drop policy if exists "Auth delete tasks" on public.tasks;
drop policy if exists "Auth read checklist" on public.task_checklist_items;
drop policy if exists "Auth insert checklist" on public.task_checklist_items;
drop policy if exists "Auth update checklist" on public.task_checklist_items;
drop policy if exists "Auth delete checklist" on public.task_checklist_items;
drop policy if exists "Auth read notes" on public.notes;
drop policy if exists "Auth insert notes" on public.notes;
drop policy if exists "Auth update notes" on public.notes;
drop policy if exists "Auth delete notes" on public.notes;
drop policy if exists "Auth read folders" on public.note_folders;
drop policy if exists "Auth insert folders" on public.note_folders;
drop policy if exists "Auth update folders" on public.note_folders;
drop policy if exists "Auth read links" on public.note_links;
drop policy if exists "Auth insert links" on public.note_links;
drop policy if exists "Auth delete links" on public.note_links;
drop policy if exists "Auth read folders" on public.folders;
drop policy if exists "Auth insert folders" on public.folders;
drop policy if exists "Auth update folders" on public.folders;
drop policy if exists "Auth delete folders" on public.folders;
drop policy if exists "Auth read files" on public.files;
drop policy if exists "Auth insert files" on public.files;
drop policy if exists "Auth update files" on public.files;
drop policy if exists "Auth delete files" on public.files;
drop policy if exists "Auth read submissions" on public.submissions;
drop policy if exists "Auth insert submissions" on public.submissions;
drop policy if exists "Auth update submissions" on public.submissions;
drop policy if exists "Auth delete submissions" on public.submissions;
drop policy if exists "Auth read deliverables" on public.submission_deliverables;
drop policy if exists "Auth insert deliverables" on public.submission_deliverables;
drop policy if exists "Auth update deliverables" on public.submission_deliverables;
drop policy if exists "Auth read checklist" on public.submission_checklist;
drop policy if exists "Auth insert checklist" on public.submission_checklist;
drop policy if exists "Auth update checklist" on public.submission_checklist;
drop policy if exists "Auth read activity" on public.activity_events;
drop policy if exists "Auth insert activity" on public.activity_events;
drop policy if exists "Auth read events" on public.hackathon_events;
drop policy if exists "Auth read pipeline" on public.event_pipeline;
drop policy if exists "Auth manage pipeline" on public.event_pipeline;
drop policy if exists "Auth update pipeline" on public.event_pipeline;
drop policy if exists "Auth read timeline" on public.event_timeline;
drop policy if exists "Auth read templates" on public.workspace_templates;
drop policy if exists "Auth insert templates" on public.workspace_templates;
drop policy if exists "Auth update templates" on public.workspace_templates;
drop policy if exists "Auth delete templates" on public.workspace_templates;
drop policy if exists "Auth read relationships" on public.relationships;
drop policy if exists "Auth insert relationships" on public.relationships;
drop policy if exists "Auth delete relationships" on public.relationships;
drop policy if exists "Users insert own notifications" on public.notifications;

create policy "Authenticated users can read hackathons" on public.hackathons for select using ((select auth.role()) = 'authenticated');
create policy "Authenticated users can create hackathons" on public.hackathons for insert with check ((select auth.role()) = 'authenticated');
create policy "Authenticated users can update hackathons" on public.hackathons for update using ((select auth.role()) = 'authenticated');
create policy "Authenticated users can delete hackathons" on public.hackathons for delete using ((select auth.role()) = 'authenticated');
create policy "Owner can read invitations" on public.invitations for select using ((select auth.role()) = 'authenticated');
create policy "Owner can create invitations" on public.invitations for insert with check ((select auth.role()) = 'authenticated');
create policy "Owner can update invitations" on public.invitations for update using ((select auth.role()) = 'authenticated');
create policy "Owner can delete invitations" on public.invitations for delete using ((select auth.role()) = 'authenticated');
create policy "Anyone can read profiles" on public.profiles for select using ((select auth.role()) = 'authenticated');
create policy "Anyone can read team members" on public.team_members for select using ((select auth.role()) = 'authenticated');
create policy "Owners can manage team members" on public.team_members for insert with check ((select auth.role()) = 'authenticated');
create policy "Owners can update team members" on public.team_members for update using ((select auth.role()) = 'authenticated');
create policy "Auth users read objectives" on public.objectives for select using ((select auth.role()) = 'authenticated');
create policy "Auth users insert objectives" on public.objectives for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth users update objectives" on public.objectives for update using ((select auth.role()) = 'authenticated');
create policy "Auth users delete objectives" on public.objectives for delete using ((select auth.role()) = 'authenticated');
create policy "Auth users read milestones" on public.milestones for select using ((select auth.role()) = 'authenticated');
create policy "Auth users insert milestones" on public.milestones for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth users update milestones" on public.milestones for update using ((select auth.role()) = 'authenticated');
create policy "Auth users delete milestones" on public.milestones for delete using ((select auth.role()) = 'authenticated');
create policy "Auth users read deliverables" on public.deliverables for select using ((select auth.role()) = 'authenticated');
create policy "Auth users insert deliverables" on public.deliverables for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth users update deliverables" on public.deliverables for update using ((select auth.role()) = 'authenticated');
create policy "Auth users delete deliverables" on public.deliverables for delete using ((select auth.role()) = 'authenticated');
create policy "Auth users read requirements" on public.requirements for select using ((select auth.role()) = 'authenticated');
create policy "Auth users insert requirements" on public.requirements for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth users update requirements" on public.requirements for update using ((select auth.role()) = 'authenticated');
create policy "Auth users delete requirements" on public.requirements for delete using ((select auth.role()) = 'authenticated');
create policy "Auth users read risks" on public.risks for select using ((select auth.role()) = 'authenticated');
create policy "Auth users insert risks" on public.risks for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth users update risks" on public.risks for update using ((select auth.role()) = 'authenticated');
create policy "Auth users delete risks" on public.risks for delete using ((select auth.role()) = 'authenticated');
create policy "Auth users read decisions" on public.decisions for select using ((select auth.role()) = 'authenticated');
create policy "Auth users insert decisions" on public.decisions for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth users update decisions" on public.decisions for update using ((select auth.role()) = 'authenticated');
create policy "Auth users delete decisions" on public.decisions for delete using ((select auth.role()) = 'authenticated');
create policy "Auth users read checklist_templates" on public.checklist_templates for select using ((select auth.role()) = 'authenticated');
create policy "Auth users insert checklist_templates" on public.checklist_templates for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth users update checklist_templates" on public.checklist_templates for update using ((select auth.role()) = 'authenticated');
create policy "Auth users delete checklist_templates" on public.checklist_templates for delete using ((select auth.role()) = 'authenticated');
create policy "Auth users read checklist_items" on public.checklist_items for select using ((select auth.role()) = 'authenticated');
create policy "Auth users insert checklist_items" on public.checklist_items for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth users update checklist_items" on public.checklist_items for update using ((select auth.role()) = 'authenticated');
create policy "Auth users delete checklist_items" on public.checklist_items for delete using ((select auth.role()) = 'authenticated');
create policy "Auth users read planning_notes" on public.planning_notes for select using ((select auth.role()) = 'authenticated');
create policy "Auth users insert planning_notes" on public.planning_notes for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth users update planning_notes" on public.planning_notes for update using ((select auth.role()) = 'authenticated');
create policy "Auth users delete planning_notes" on public.planning_notes for delete using ((select auth.role()) = 'authenticated');
create policy "Auth read ideas" on public.ideas for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert ideas" on public.ideas for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update ideas" on public.ideas for update using ((select auth.role()) = 'authenticated');
create policy "Auth delete ideas" on public.ideas for delete using ((select auth.role()) = 'authenticated');
create policy "Auth read votes" on public.idea_votes for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert votes" on public.idea_votes for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth delete votes" on public.idea_votes for delete using ((select auth.role()) = 'authenticated');
create policy "Auth read research" on public.research_items for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert research" on public.research_items for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update research" on public.research_items for update using ((select auth.role()) = 'authenticated');
create policy "Auth delete research" on public.research_items for delete using ((select auth.role()) = 'authenticated');
create policy "Auth read tasks" on public.tasks for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert tasks" on public.tasks for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update tasks" on public.tasks for update using ((select auth.role()) = 'authenticated');
create policy "Auth delete tasks" on public.tasks for delete using ((select auth.role()) = 'authenticated');
create policy "Auth read checklist" on public.task_checklist_items for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert checklist" on public.task_checklist_items for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update checklist" on public.task_checklist_items for update using ((select auth.role()) = 'authenticated');
create policy "Auth delete checklist" on public.task_checklist_items for delete using ((select auth.role()) = 'authenticated');
create policy "Auth read notes" on public.notes for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert notes" on public.notes for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update notes" on public.notes for update using ((select auth.role()) = 'authenticated');
create policy "Auth delete notes" on public.notes for delete using ((select auth.role()) = 'authenticated');
create policy "Auth read folders" on public.note_folders for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert folders" on public.note_folders for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update folders" on public.note_folders for update using ((select auth.role()) = 'authenticated');
create policy "Auth read links" on public.note_links for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert links" on public.note_links for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth delete links" on public.note_links for delete using ((select auth.role()) = 'authenticated');
create policy "Auth read folders" on public.folders for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert folders" on public.folders for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update folders" on public.folders for update using ((select auth.role()) = 'authenticated');
create policy "Auth delete folders" on public.folders for delete using ((select auth.role()) = 'authenticated');
create policy "Auth read files" on public.files for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert files" on public.files for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update files" on public.files for update using ((select auth.role()) = 'authenticated');
create policy "Auth delete files" on public.files for delete using ((select auth.role()) = 'authenticated');
create policy "Auth read submissions" on public.submissions for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert submissions" on public.submissions for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update submissions" on public.submissions for update using ((select auth.role()) = 'authenticated');
create policy "Auth delete submissions" on public.submissions for delete using ((select auth.role()) = 'authenticated');
create policy "Auth read deliverables" on public.submission_deliverables for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert deliverables" on public.submission_deliverables for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update deliverables" on public.submission_deliverables for update using ((select auth.role()) = 'authenticated');
create policy "Auth read checklist" on public.submission_checklist for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert checklist" on public.submission_checklist for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update checklist" on public.submission_checklist for update using ((select auth.role()) = 'authenticated');
create policy "Auth read activity" on public.activity_events for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert activity" on public.activity_events for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth read events" on public.hackathon_events for select using ((select auth.role()) = 'authenticated');
create policy "Auth read pipeline" on public.event_pipeline for select using ((select auth.role()) = 'authenticated');
create policy "Auth manage pipeline" on public.event_pipeline for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update pipeline" on public.event_pipeline for update using ((select auth.role()) = 'authenticated');
create policy "Auth read timeline" on public.event_timeline for select using ((select auth.role()) = 'authenticated');
create policy "Auth read templates" on public.workspace_templates for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert templates" on public.workspace_templates for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth update templates" on public.workspace_templates for update using ((select auth.role()) = 'authenticated');
create policy "Auth delete templates" on public.workspace_templates for delete using ((select auth.role()) = 'authenticated');
create policy "Auth read relationships" on public.relationships for select using ((select auth.role()) = 'authenticated');
create policy "Auth insert relationships" on public.relationships for insert with check ((select auth.role()) = 'authenticated');
create policy "Auth delete relationships" on public.relationships for delete using ((select auth.role()) = 'authenticated');
create policy "Users insert own notifications" on public.notifications for insert with check ((select auth.role()) = 'authenticated');

-- Notify reindexing complete
-- All auth.role() calls now wrapped in SELECT for plan-stability

